import React from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const countries = [
  { value: "afg", label: "Afghanistan" },
  { value: "alb", label: "Albania" },
  { value: "dza", label: "Algeria" },
  { value: "and", label: "Andorra" },
  { value: "ago", label: "Angola" },
  { value: "atg", label: "Antigua and Barbuda" },
  { value: "arg", label: "Argentina" },
  { value: "arm", label: "Armenia" },
  { value: "aus", label: "Australia" },
  { value: "aut", label: "Austria" },
  { value: "aze", label: "Azerbaijan" },
  { value: "bhs", label: "Bahamas" },
  { value: "bhr", label: "Bahrain" },
  { value: "bgd", label: "Bangladesh" },
  { value: "brb", label: "Barbados" },
  { value: "blr", label: "Belarus" },
  { value: "bel", label: "Belgium" },
  { value: "blz", label: "Belize" },
  { value: "ben", label: "Benin" },
  { value: "btn", label: "Bhutan" },
  { value: "bol", label: "Bolivia" },
  { value: "bih", label: "Bosnia and Herzegovina" },
  { value: "bra", label: "Brazil" },
  { value: "brn", label: "Brunei" },
  { value: "bgr", label: "Bulgaria" },
  { value: "bfa", label: "Burkina Faso" },
  { value: "bdi", label: "Burundi" },
  { value: "khm", label: "Cambodia" },
  { value: "cmr", label: "Cameroon" },
  { value: "can", label: "Canada" },
  { value: "caf", label: "Central African Republic" },
  { value: "tcd", label: "Chad" },
  { value: "chl", label: "Chile" },
  { value: "chn", label: "China" },
  { value: "col", label: "Colombia" },
  { value: "com", label: "Comoros" },
  { value: "cog", label: "Congo" },
  { value: "cod", label: "Congo (DRC)" },
  { value: "cri", label: "Costa Rica" },
  { value: "hrv", label: "Croatia" },
  { value: "cub", label: "Cuba" },
  { value: "cyp", label: "Cyprus" },
  { value: "cze", label: "Czech Republic" },
  { value: "dnk", label: "Denmark" },
  { value: "dji", label: "Djibouti" },
  { value: "dma", label: "Dominica" },
  { value: "dom", label: "Dominican Republic" },
  { value: "ecu", label: "Ecuador" },
  { value: "egy", label: "Egypt" },
  { value: "slv", label: "El Salvador" },
  { value: "gnq", label: "Equatorial Guinea" },
  { value: "eri", label: "Eritrea" },
  { value: "est", label: "Estonia" },
  { value: "eth", label: "Ethiopia" },
  { value: "fji", label: "Fiji" },
  { value: "fin", label: "Finland" },
  { value: "fra", label: "France" },
  { value: "gab", label: "Gabon" },
  { value: "gmb", label: "Gambia" },
  { value: "geo", label: "Georgia" },
  { value: "deu", label: "Germany" },
  { value: "gha", label: "Ghana" },
  { value: "grc", label: "Greece" },
  { value: "grd", label: "Grenada" },
  { value: "gtm", label: "Guatemala" },
  { value: "gin", label: "Guinea" },
  { value: "gnb", label: "Guinea-Bissau" },
  { value: "guy", label: "Guyana" },
  { value: "hti", label: "Haiti" },
  { value: "hnd", label: "Honduras" },
  { value: "hun", label: "Hungary" },
  { value: "isl", label: "Iceland" },
  { value: "ind", label: "India" },
  { value: "idn", label: "Indonesia" },
  { value: "irn", label: "Iran" },
  { value: "irq", label: "Iraq" },
  { value: "irl", label: "Ireland" },
  { value: "isr", label: "Israel" },
  { value: "ita", label: "Italy" },
  { value: "jam", label: "Jamaica" },
  { value: "jpn", label: "Japan" },
  { value: "jor", label: "Jordan" },
  { value: "kaz", label: "Kazakhstan" },
  { value: "ken", label: "Kenya" },
  { value: "kir", label: "Kiribati" },
  { value: "prk", label: "North Korea" },
  { value: "kor", label: "South Korea" },
  { value: "kwt", label: "Kuwait" },
  { value: "kgz", label: "Kyrgyzstan" },
  { value: "lao", label: "Laos" },
  { value: "lva", label: "Latvia" },
  { value: "lbn", label: "Lebanon" },
  { value: "lso", label: "Lesotho" },
  { value: "lbr", label: "Liberia" },
  { value: "lby", label: "Libya" },
  { value: "lie", label: "Liechtenstein" },
  { value: "ltu", label: "Lithuania" },
  { value: "lux", label: "Luxembourg" },
  { value: "mdg", label: "Madagascar" },
  { value: "mwi", label: "Malawi" },
  { value: "mys", label: "Malaysia" },
  { value: "mdv", label: "Maldives" },
  { value: "mli", label: "Mali" },
  { value: "mlt", label: "Malta" },
  { value: "mhl", label: "Marshall Islands" },
  { value: "mrt", label: "Mauritania" },
  { value: "mus", label: "Mauritius" },
  { value: "mex", label: "Mexico" },
  { value: "fsm", label: "Micronesia" },
  { value: "mda", label: "Moldova" },
  { value: "mco", label: "Monaco" },
  { value: "mng", label: "Mongolia" },
  { value: "mne", label: "Montenegro" },
  { value: "mar", label: "Morocco" },
  { value: "moz", label: "Mozambique" },
  { value: "mmr", label: "Myanmar" },
  { value: "nam", label: "Namibia" },
  { value: "nru", label: "Nauru" },
  { value: "npl", label: "Nepal" },
  { value: "nld", label: "Netherlands" },
  { value: "nzl", label: "New Zealand" },
  { value: "nic", label: "Nicaragua" },
  { value: "ner", label: "Niger" },
  { value: "nga", label: "Nigeria" },
  { value: "mkd", label: "North Macedonia" },
  { value: "nor", label: "Norway" },
  { value: "omn", label: "Oman" },
  { value: "pak", label: "Pakistan" },
  { value: "plw", label: "Palau" },
  { value: "pan", label: "Panama" },
  { value: "png", label: "Papua New Guinea" },
  { value: "pry", label: "Paraguay" },
  { value: "per", label: "Peru" },
  { value: "phl", label: "Philippines" },
  { value: "pol", label: "Poland" },
  { value: "prt", label: "Portugal" },
  { value: "qat", label: "Qatar" },
  { value: "rou", label: "Romania" },
  { value: "rus", label: "Russia" },
  { value: "rwa", label: "Rwanda" },
  { value: "kna", label: "Saint Kitts and Nevis" },
  { value: "lca", label: "Saint Lucia" },
  { value: "vct", label: "Saint Vincent and the Grenadines" },
  { value: "wsm", label: "Samoa" },
  { value: "smr", label: "San Marino" },
  { value: "stp", label: "São Tomé and Príncipe" },
  { value: "sau", label: "Saudi Arabia" },
  { value: "sen", label: "Senegal" },
  { value: "srb", label: "Serbia" },
  { value: "syc", label: "Seychelles" },
  { value: "sle", label: "Sierra Leone" },
  { value: "sgp", label: "Singapore" },
  { value: "svk", label: "Slovakia" },
  { value: "svn", label: "Slovenia" },
  { value: "slb", label: "Solomon Islands" },
  { value: "som", label: "Somalia" },
  { value: "zaf", label: "South Africa" },
  { value: "ssd", label: "South Sudan" },
  { value: "esp", label: "Spain" },
  { value: "lka", label: "Sri Lanka" },
  { value: "sdn", label: "Sudan" },
  { value: "sur", label: "Suriname" },
  { value: "swz", label: "Eswatini" },
  { value: "swe", label: "Sweden" },
  { value: "che", label: "Switzerland" },
  { value: "syr", label: "Syria" },
  { value: "twn", label: "Taiwan" },
  { value: "tjk", label: "Tajikistan" },
  { value: "tza", label: "Tanzania" },
  { value: "tha", label: "Thailand" },
  { value: "tls", label: "Timor-Leste" },
  { value: "tgo", label: "Togo" },
  { value: "ton", label: "Tonga" },
  { value: "tto", label: "Trinidad and Tobago" },
  { value: "tun", label: "Tunisia" },
  { value: "tur", label: "Turkey" },
  { value: "tkm", label: "Turkmenistan" },
  { value: "tuv", label: "Tuvalu" },
  { value: "uga", label: "Uganda" },
  { value: "ukr", label: "Ukraine" },
  { value: "are", label: "United Arab Emirates" },
  { value: "gbr", label: "United Kingdom" },
  { value: "usa", label: "United States" },
  { value: "ury", label: "Uruguay" },
  { value: "uzb", label: "Uzbekistan" },
  { value: "vut", label: "Vanuatu" },
  { value: "ven", label: "Venezuela" },
  { value: "vnm", label: "Vietnam" },
  { value: "yem", label: "Yemen" },
  { value: "zmb", label: "Zambia" },
  { value: "zwe", label: "Zimbabwe" },
];

interface CountrySelectorProps {
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  disabled?: boolean;
}

const CountrySelector: React.FC<CountrySelectorProps> = ({
  value,
  defaultValue,
  onValueChange,
  disabled,
}) => {
  return (
    <Select
      value={value}
      defaultValue={defaultValue}
      onValueChange={onValueChange}
      disabled={disabled}
    >
      <SelectTrigger className="w-auto inline-flex items-center gap-2 bg-[#0D0D0D] border-2 border-white/10 text-white font-semibold rounded-xl px-3 py-2 h-auto focus:ring-0 focus:ring-offset-0">
        <SelectValue placeholder="Select" />
      </SelectTrigger>
      <SelectContent className="bg-[#1C1C1E] text-white border-white/20">
        {countries.map((country) => (
          <SelectItem
            value={country.value}
            key={country.value}
            className="focus:bg-blue-500 focus:text-white"
          >
            {country.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
};

export default CountrySelector;
